# Refer https://docs.halo.run/developer-guide/plugin/basics/manifest

apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  # The name defines how the plugin is invoked, A unique name
  name: online
spec:
  version: "1.0.5"
  enabled: true
  requires: ">=2.23.0"
  author:
    name: Zyx-2012
    website: https://blog.zyx-2012.cn
  logo: logo.png
  homepage: https://github.com/Zyx-2012/plugin-online#readme
  repo: https://github.com/Zyx-2012/plugin-online
  issues: https://github.com/Zyx-2012/plugin-online/issues
  displayName: "在线显示"
  description: "让用户看到有多少人在与他看同一个页面"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/Zyx-2012/plugin-online/blob/main/LICENSE"
  settingName: "online-settings"
  configMapName: "online-configmap"
